mysite/cats/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'cats'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
    path('lookup/', views.BreedView.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete'),
]

mysite/gadgets/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'gadgets'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.GadgetCreate.as_view(), name='gadget_create'),
    path('main/<int:pk>/update/', views.GadgetUpdate.as_view(), name='gadget_update'),
    path('main/<int:pk>/delete/', views.GadgetDelete.as_view(), name='gadget_delete'),
    path('lookup/', views.BrandView.as_view(), name='brand_list'),
    path('lookup/create/', views.BrandCreate.as_view(), name='brand_create'),
    path('lookup/<int:pk>/update/', views.BrandUpdate.as_view(), name='brand_update'),
    path('lookup/<int:pk>/delete/', views.BrandDelete.as_view(), name='brand_delete'),
]

mysite/mysite/urls.py
import os
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.urls import include, path
from django.conf.urls import url
from django.views.static import serve

# Up two folders to serve "site" content
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE_ROOT = os.path.join(BASE_DIR, 'site')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home/main.html')),
    path('hello',  include('hello.urls')),
    path('polls/', include('polls.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('autos/', include('autos.urls')),
    path('cats/', include('cats.urls')),
    path('gadgets/', include('gadgets.urls')),
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': SITE_ROOT, 'show_indexes': True},
        name='site_path'
    ),
]

mysite/gadgets/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Brand(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Brand must be greater than 1 character")]
    )

    def __str__(self):
        return self.name

class Gadget(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    price = models.PositiveIntegerField()
    year = models.PositiveIntegerField()
    notes = models.CharField(max_length=300)
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

mysite/gadgets/forms.py
from django.forms import ModelForm
from gadgets.models import Brand


# Create the form class.
class BrandForm(ModelForm):
    class Meta:
        model = Brand
        fields = '__all__'

mysite/gadgets/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from gadgets.models import Brand, Gadget
from gadgets.forms import BrandForm

# Create your views here.


class MainView(LoginRequiredMixin, View):
    def get(self, request):
        br_cnt = Brand.objects.all().count()
        ca_list = Gadget.objects.all()

        ctx = {'brand_count': br_cnt, 'gadget_list': ca_list}
        return render(request, 'gadgets/gadget_list.html', ctx)


class BrandView(LoginRequiredMixin, View):
    def get(self, request):
        br_list = Brand.objects.all()
        ctx = {'brand_list': br_list}
        return render(request, 'gadgets/brand_list.html', ctx)


# We use reverse_lazy() because we are in "constructor attribute" code
# that is run before urls.py is completely loaded
class BrandCreate(LoginRequiredMixin, View):
    template = 'gadgets/brand_form.html'
    success_url = reverse_lazy('gadgets:all')

    def get(self, request):
        form = BrandForm()
        ctx = {'form': form}
        return render(request, self.template, ctx)

    def post(self, request):
        form = BrandForm(request.POST)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)

        brand = form.save()
        return redirect(self.success_url)


# MakeUpdate has code to implement the get/post/validate/store flow
# AutoUpdate (below) is doing the same thing with no code
# and no form by extending UpdateView
class BrandUpdate(LoginRequiredMixin, View):
    model = Brand
    success_url = reverse_lazy('gadgets:all')
    template = 'gadgets/brand_form.html'

    def get(self, request, pk):
        brand = get_object_or_404(self.model, pk=pk)
        form = BrandForm(instance=brand)
        ctx = {'form': form}
        return render(request, self.template, ctx)

    def post(self, request, pk):
        brand = get_object_or_404(self.model, pk=pk)
        form = BrandForm(request.POST, instance=brand)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)

        form.save()
        return redirect(self.success_url)


class BrandDelete(LoginRequiredMixin, View):
    model = Brand
    success_url = reverse_lazy('gadgets:all')
    template = 'gadgets/brand_confirm_delete.html'

    def get(self, request, pk):
        brand = get_object_or_404(self.model, pk=pk)
        form = BrandForm(instance=brand)
        ctx = {'brand': brand}
        return render(request, self.template, ctx)

    def post(self, request, pk):
        brand = get_object_or_404(self.model, pk=pk)
        brand.delete()
        return redirect(self.success_url)


# Take the easy way out on the main table
# These views do not need a form because CreateView, etc.
# Build a form object dynamically based on the fields
# value in the constructor attributes
class GadgetCreate(LoginRequiredMixin, CreateView):
    model = Gadget
    fields = '__all__'
    success_url = reverse_lazy('gadgets:all')


class GadgetUpdate(LoginRequiredMixin, UpdateView):
    model = Gadget
    fields = '__all__'
    success_url = reverse_lazy('gadgets:all')


class GadgetDelete(LoginRequiredMixin, DeleteView):
    model = Gadget
    fields = '__all__'
    success_url = reverse_lazy('gadgets:all')

mysite/gadgets/templates/gadgets/brand_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Brand</h1>

<p>Are you sure you want to delete the brand: {{ brand }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'gadgets:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

mysite/gadgets/templates/gadgets/brand_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'gadgets:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/gadgets/templates/gadgets/brand_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Brand List</h1>
  {% if brand_list %}
  <ul>
    {% for brand in brand_list %}
      <li>
          {{ brand.name }}
         (<a href="{% url 'gadgets:brand_update' brand.id %}">Update</a> |
          <a href="{% url 'gadgets:brand_delete' brand.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no brands in the library.</p>
  {% endif %}
  <p><a href="{% url 'gadgets:brand_create' %}">Add a brand</a></p>
  <p>
    <a href="{% url 'gadgets:all' %}">Back to gadgets</a>
  </p>
{% endblock %}

mysite/gadgets/templates/gadgets/gadget_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Gadget</h1>

<p>Are you sure you want to delete the gadget: {{ gadget }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mysite/gadgets/templates/gadgets/gadget_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'gadgets:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

mysite/gadgets/templates/gadgets/gadget_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Gadgets List</h1>
  {% if gadget_list %}
  <ul>
    {% for gadget in gadget_list %}
      <li>
          {{ gadget.nickname }} ({{ gadget.brand }})
          (<a href="{% url 'gadgets:gadget_update' gadget.id %}">Update</a> |
          <a href="{% url 'gadgets:gadget_delete' gadget.id %}">Delete</a>) <br/>
          {{ gadget.year }} year ({{ gadget.notes }} )
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no gadgets in the library.</p>
  {% endif %}
  <p>
    {% if brand_count > 0 %}
      <a href="{% url 'gadgets:gadget_create' %}">Add a gadget</a>
    {% else %}
      Please add a brand before you add a gadget.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'gadgets:brand_list' %}">View brands</a> ({{ brand_count }}) | 
    <a href="{% url 'gadgets:brand_create' %}">Add a brand</a>
  </p>
{% endblock %}